title: GFM Demo
description: GitHub Flavored Markdown on GitHub Pages (Jekyll)
theme: minima

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
    span:
      line_numbers: false

permalink: pretty
baseurl: ""
url: ""

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/yourname
