title: GFM Demo
description: GitHub Flavored Markdown on GitHub Pages (Jekyll)
theme: minima

# Ensure GFM parsing
markdown: kramdown
kramdown:
  input: GFM

# Permalinks etc.
permalink: pretty

# (Optional) Set baseurl if deploying to a project page (e.g., /my-repo). Leave empty for user/organization site.
baseurl: ""
url: ""

# Minima options
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/yourname
